/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zanis
 */
public class Splash_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Splash_Panel
     */
    public Splash_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();
        lbl_logo2 = new javax.swing.JLabel();
        lbl_logo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        bar.setText("0%");
        add(bar);
        bar.setBounds(400, 530, 30, 16);
        add(prog);
        prog.setBounds(190, 510, 455, 12);

        lbl_logo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_logo2.setForeground(new java.awt.Color(246, 152, 22));
        add(lbl_logo2);
        lbl_logo2.setBounds(20, 120, 63, 40);

        lbl_logo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_logo1.setForeground(new java.awt.Color(161, 197, 252));
        lbl_logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zanis\\Desktop\\JavaGram\\image\\logo_icon.png")); // NOI18N
        add(lbl_logo1);
        lbl_logo1.setBounds(20, 10, 60, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zanis\\Desktop\\JavaGram\\image\\sn_gif.gif")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 490);

        jLabel2.setForeground(new java.awt.Color(9, 0, 49));
        jLabel2.setText("Development and Design By : M.Taghizadeh");
        add(jLabel2);
        jLabel2.setBounds(280, 560, 250, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_logo1;
    public javax.swing.JLabel lbl_logo2;
    public javax.swing.JProgressBar prog;
    // End of variables declaration//GEN-END:variables
}
